platform :ios do
  lane :react_native_build_ios_app do |options|
    build_app(
      destination: "generic/platform=iOS",
      workspace: "./example/reactnative/ios/reactNativeExample.xcworkspace",
      scheme: "reactNativeExample",
      configuration: "Release",
      export_options: "./example/reactnative/ios/ExportOptions.plist",
      clean: true,
      output_directory: "./build/Release/iOS/reactNativeExample",
      output_name: "reactNativeExample.ipa",
      xcargs: "CURRENT_PROJECT_VERSION=#{options[:CURRENT_PROJECT_VERSION]}",
    )
  end

  lane :capacitor_build_ios_simulator do
    xcodebuild(
      build: true,
      destination: "generic/platform=iOS Simulator",
      workspace: "./example/capacitor/ios/App/App.xcworkspace",
      scheme: "App",
    )
  end

  lane :capacitor_build_ios_app do |options|
    build_app(
      destination: "generic/platform=iOS",
      workspace: "./example/capacitor/ios/App/App.xcworkspace",
      scheme: "App",
      configuration: "Release",
      export_options: "./example/capacitor/ios/App/ExportOptions.plist",
      clean: true,
      output_directory: "./build/Release/iOS/capacitor",
      output_name: "capacitor.ipa",
      xcargs: "CURRENT_PROJECT_VERSION=#{options[:CURRENT_PROJECT_VERSION]}",
    )
  end

  lane :upload_ios_app do |options|
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      api_key_path: "./build/fastlane-api-key.json",
      ipa: options[:ipa],
    )
  end
end

platform :android do
  lane :react_native_build_aab do |options|
    gradle(
      project_dir: "./example/reactnative/android",
      tasks: [":app:bundleRelease"],
      properties: {
        "VERSION_CODE" => options[:VERSION_CODE],
        "STORE_FILE" => options[:STORE_FILE],
        "STORE_PASSWORD" => options[:STORE_PASSWORD],
        "KEY_ALIAS" => options[:KEY_ALIAS],
        "KEY_PASSWORD" => options[:KEY_PASSWORD],
      },
    )
  end

  lane :react_native_upload_aab do |options|
    upload_to_play_store(
      json_key: options[:json_key],
      package_name: "com.authgear.sdk.exampleapp.reactnative",
      track: "internal",
      aab: "./example/reactnative/android/app/build/outputs/bundle/release/app-release.aab",
    )
  end

  lane :capacitor_build_aab do |options|
    gradle(
      project_dir: "./example/capacitor/android",
      tasks: [":app:bundleRelease"],
      properties: {
        "VERSION_CODE" => options[:VERSION_CODE],
        "STORE_FILE" => options[:STORE_FILE],
        "STORE_PASSWORD" => options[:STORE_PASSWORD],
        "KEY_ALIAS" => options[:KEY_ALIAS],
        "KEY_PASSWORD" => options[:KEY_PASSWORD],
      },
    )
  end

  lane :capacitor_upload_aab do |options|
    upload_to_play_store(
      json_key: options[:json_key],
      package_name: "com.authgear.sdk.exampleapp.capacitor",
      track: "internal",
      aab: "./example/capacitor/android/app/build/outputs/bundle/release/app-release.aab",
    )
  end
end
